version: '3.4'

services:

  sqlserver:
    environment:
      - SA_PASSWORD=Admin123456
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"


  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    ports:
      - "5379:6379"

  zipkin:
    ports:
      - "5411:9411"


  shopping.api.order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_orderdb;Persist Security Info=True;User ID=sa;Password=Admin123456
      - MemberIdentityServerUrl=http://${LOCALHOST_IP}:5101
      - TenantIdentityServerUrl=http://${LOCALHOST_IP}:5102
      - ApiName=orderapi
    ports:
      - "5001:80"
  shopping.api.order.dapr:
    command: [ "./daprd",
    "-app-id", "orderapi", # app-id不可以有 .   这个写法 ordering.api 是错误的
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  shopping.api.member:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_memberdb;Persist Security Info=True;User ID=sa;Password=Admin123456
      - MemberIdentityServerUrl=http://${LOCALHOST_IP}:5101
      - TenantIdentityServerUrl=http://${LOCALHOST_IP}:5102
      - ApiName=memberapi
    ports:
      - "5002:80"
  shopping.api.member.dapr:
    command: [ "./daprd",
    "-app-id", "memberapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  shopping.api.pay:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_paydb;Persist Security Info=True;User ID=sa;Password=Admin123456
      - MemberIdentityServerUrl=http://${LOCALHOST_IP}:5101
      - TenantIdentityServerUrl=http://${LOCALHOST_IP}:5102
      - ApiName=payapi
    ports:
      - "5003:80"
  shopping.api.pay.dapr:
    command: [ "./daprd",
    "-app-id", "payapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  shopping.api.product:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_productdb;Persist Security Info=True;User ID=sa;Password=Admin123456
      - MemberIdentityServerUrl=http://${LOCALHOST_IP}:5101
      - TenantIdentityServerUrl=http://${LOCALHOST_IP}:5102
      - ApiName=productapi
    ports:
      - "80"
  shopping.api.product.dapr:
    command: [ "./daprd",
    "-app-id", "productapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  shopping.api.tenant:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_tenantdb;Persist Security Info=True;User ID=sa;Password=Admin123456
      - MemberIdentityServerUrl=http://${LOCALHOST_IP}:5101
      - TenantIdentityServerUrl=http://${LOCALHOST_IP}:5102
      - ApiName=tenantapi
    ports:
      - "5005:80"
  shopping.api.tenant.dapr:
    command: [ "./daprd",
    "-app-id", "tenantapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  shopping.api.identitymember:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_memberdb;Persist Security Info=True;User ID=sa;Password=Admin123456
      - JSUrl=http://${LOCALHOST_IP}:5201
    ports:
      - "5101:80"

  shopping.api.identitytenant:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_tenantdb;Persist Security Info=True;User ID=sa;Password=Admin123456
      - JSUrl=http://${LOCALHOST_IP}:5202
    ports:
      - "5102:80"


  nginxgateway:
    ports:
      - "5200:80"




