version: '3.4'

services:
  # docker run -d -p 7433:1433 -e SA_PASSWORD=Admin123456 -e ACCEPT_EULA=Y  mcr.microsoft.com/mssql/server:2019-latest
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Order.Api/Dockerfile


  member.api:
    image: ${DOCKER_REGISTRY-}memberapi
    build:
      context: .
      dockerfile: Member.Api/Dockerfile


  pay.api:
    image: ${DOCKER_REGISTRY-}payapi
    build:
      context: .
      dockerfile: Pay.Api/Dockerfile


  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Product.Api/Dockerfile


  tenant.api:
    image: ${DOCKER_REGISTRY-}tenantapi
    build:
      context: .
      dockerfile: Tenant.Api/Dockerfile


  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: IdentityMember.Api/Dockerfile

