version: '3.4'

services:

  sqlserver:
    environment:
      - SA_PASSWORD=Admin123456
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"


  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    ports:
      - "5379:6379"

  zipkin:
    ports:
      - "5411:9411"


  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_orderdb;Persist Security Info=True;User ID=sa;Password=Admin123456
    ports:
      - "80"


  member.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_memberdb;Persist Security Info=True;User ID=sa;Password=Admin123456
    ports:
      - "80"


  pay.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_paydb;Persist Security Info=True;User ID=sa;Password=Admin123456
    ports:
      - "80"


  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_productdb;Persist Security Info=True;User ID=sa;Password=Admin123456
    ports:
      - "80"


  tenant.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_tenantdb;Persist Security Info=True;User ID=sa;Password=Admin123456
    ports:
      - "80"


  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Data Source=sqlserver;Initial Catalog=shopping_memberdb;Persist Security Info=True;User ID=sa;Password=Admin123456
    ports:
      - "80"
      - "443"
