version: '3.4'

services:
  # docker run -d -p 7433:1433 -e SA_PASSWORD=Admin123456 -e ACCEPT_EULA=Y  mcr.microsoft.com/mssql/server:2019-latest
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim


  shopping.api.order:
    image: ${DOCKER_REGISTRY-}shoppingapiorder
    build:
      context: .
      dockerfile: Shopping.Api.Order/Dockerfile
  shopping.api.order.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - shopping.api.order
    network_mode: "service:shopping.api.order"


  shopping.api.member:
    image: ${DOCKER_REGISTRY-}shoppingapimember
    build:
      context: .
      dockerfile: Shopping.Api.Member/Dockerfile
  shopping.api.member.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - shopping.api.member
    network_mode: "service:shopping.api.member"

  shopping.api.pay:
    image: ${DOCKER_REGISTRY-}shoppingapipay
    build:
      context: .
      dockerfile: Shopping.Api.Pay/Dockerfile
  shopping.api.pay.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - shopping.api.pay
    network_mode: "service:shopping.api.pay"

  shopping.api.product:
    image: ${DOCKER_REGISTRY-}shoppingapiproduct
    build:
      context: .
      dockerfile: Shopping.Api.Product/Dockerfile
  shopping.api.product.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - shopping.api.product
    network_mode: "service:shopping.api.product"

  shopping.api.tenant:
    image: ${DOCKER_REGISTRY-}shoppingapitenant
    build:
      context: .
      dockerfile: Shopping.Api.Tenant/Dockerfile
  shopping.api.tenant.dapr:
    image: "daprio/daprd:latest"
    depends_on:
      - shopping.api.tenant
    network_mode: "service:shopping.api.tenant"

  shopping.api.identitymember:
    image: ${DOCKER_REGISTRY-}shoppingapiidentitymember
    build:
      context: .
      dockerfile: Shopping.Api.IdentityMember/Dockerfile


  shopping.api.identitytenant:
    image: ${DOCKER_REGISTRY-}shoppingapiidentitytenant
    build:
      context: .
      dockerfile: Shopping.Api.IdentityTenant/Dockerfile
  
  nginxgateway:
    image: nginxgateway
    build:
      context: .
      dockerfile: gateways/nginxgateway/Dockerfile



