version: '3.4'

services:
  mysql:
    image: mysql:latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Order.Api/Dockerfile
