version: '3.4'

services:

  #sqlserver:
  #  container_name: shopping_sqlserver
  #  environment:
  #    - SA_PASSWORD=Admin123456
  #    - ACCEPT_EULA=Y
  #  ports:
  #    - "5433:1433"

  mysql:
    container_name: shopping_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - D://docker/shoppingmysql/db:/var/lib/mysql
      - D://docker/shoppingmysql/config:/etc/my.cnf
    ports:
      - "3307:3306"

  rabbitmq:
    container_name: shopping_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: shopping_redis
    ports:
      - "5379:6379"

  zipkin:
    container_name: shopping_zipkin
    ports:
      - "5411:9411"


  shopping.api.order:
    container_name: shopping_order
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=order_db;user ID=root;Password=123456;
      - MemberIdentityServerUrl=http://${LOCALHOST_IP}:5101
      - TenantIdentityServerUrl=http://${LOCALHOST_IP}:5102
      - ApiName=orderapi
    ports:
      - "5001:80"
  shopping.api.order.dapr:
    container_name: shopping_order_dapr
    command: [ "./daprd",
    "-app-id", "orderapi", # app-id不可以有 .   这个写法 ordering.api 是错误的
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  shopping.api.member:
    container_name: shopping_member
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=member_db;user ID=root;Password=123456;
      - MemberIdentityServerUrl=http://${LOCALHOST_IP}:5101
      - TenantIdentityServerUrl=http://${LOCALHOST_IP}:5102
      - ApiName=memberapi
    ports:
      - "5002:80"
  shopping.api.member.dapr:
    container_name: shopping_member_dapr
    command: [ "./daprd",
    "-app-id", "memberapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  shopping.api.pay:
    container_name: shopping_pay
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=pay_db;user ID=root;Password=123456;
      - MemberIdentityServerUrl=http://${LOCALHOST_IP}:5101
      - TenantIdentityServerUrl=http://${LOCALHOST_IP}:5102
      - ApiName=payapi
    ports:
      - "5003:80"
  shopping.api.pay.dapr:
    container_name: shopping_pay_dapr
    command: [ "./daprd",
    "-app-id", "payapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  shopping.api.product:
    container_name: shopping_product
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=product_db;user ID=root;Password=123456;
      - MemberIdentityServerUrl=http://${LOCALHOST_IP}:5101
      - TenantIdentityServerUrl=http://${LOCALHOST_IP}:5102
      - ApiName=productapi
    ports:
      - "5004:80"
  shopping.api.product.dapr:
    container_name: shopping_product_dapr
    command: [ "./daprd",
    "-app-id", "productapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  shopping.api.tenant:
    container_name: shopping_tenant
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=tenant_db;user ID=root;Password=123456;
      - MemberIdentityServerUrl=http://${LOCALHOST_IP}:5101
      - TenantIdentityServerUrl=http://${LOCALHOST_IP}:5102
      - ApiName=tenantapi
    ports:
      - "5005:80"
  shopping.api.tenant.dapr:
    container_name: shopping_tenant_dapr
    command: [ "./daprd",
    "-app-id", "tenantapi",
    "-app-port", "80",
    "-components-path", "/components",
    "-config", "/configuration/eshop-config.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  shopping.api.identitymember:
    container_name: shopping_identitymember
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=member_db;user ID=root;Password=123456;
      - JSUrl=http://${LOCALHOST_IP}:5201
    ports:
      - "5101:80"

  shopping.api.identitytenant:
    container_name: shopping_identitytenant
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Data Source=mysql;port=3306;Initial Catalog=tenant_db;user ID=root;Password=123456;
      - JSUrl=http://${LOCALHOST_IP}:5202
    ports:
      - "5102:80"


  nginxgateway:
    container_name: shopping_nginxgateway
    ports:
      - "5200:80"





  shopping.api.oss:
    container_name: shopping_oss
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - D://docker/shoppingfile:/app/wwwroot
    ports:
      - "5006:80"

